# Generated by Django 4.2.1 on 2023-06-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_proveedor_alter_clientes_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
